### ISSUE TITLE
Question: Why assign variables to lodash functions?

### ISSUE THREAD

**Issue by reggi** [megawac/acorn-umd#3]
[Early in the library](https://github.com/megawac/acorn-umd/blob/master/dist/acorn-umd.js#L7-L17) you assign variables to all the lodash function you use in the file. I was wondering what your reasoning was behind this?

**Comment by reggi** [comment]
At first glance it seems that this allows for using both underscore and lodash, or switching back and forth if necessary. Is that why?

**Comment by megawac** [comment]
On my phone but thats a file compiled by babel. See the source code in the src/ folder.

Anyway there's no particular reason I do that, I just wanted to use es6 imports

**Comment by reggi** [comment]
Thanks for the explanation!
